package constant

const (
	ServerError = "服务器错误"

	EstablishWebsocketConnectFail      = "建立websocket连接失败"
	ConnectedUserNotFound              = "连接用户不存在"
	ConnectedUserNotOnline             = "连接用户不在线"
	ConnectCut                         = "连接断开"
	RedisUserHeartbeatPrefix           = "user:heartbeat:"
	ConnectedUserSuccess               = "连接用户成功"
	ChatEstablishSuccess               = "聊天建立成功"
	ChatEstablishSuccessFrom           = "聊天建立成功:"
	ChatEstablishFailFrom              = "聊天建立失败:"
	ChatEstablishFailTo                = "建立到对象的聊天失败:"
	RespCutChatMessageSuccess          = "聊天断开成功"
	RespChatCutFrom                    = "聊天断开:"
	RespNotConnect                     = "未连接"
	RespChatterDisconnected            = "聊天用户连接断开"
	RespCutChatFailed                  = "聊天断开失败"
	RespEstablishChatMessageFromPrefix = "establish_chat_from:"
	ConnectedUserNotFoundInChatList    = "连接用户不在聊天列表中"
	ConnectedUserAlreadyOnline         = "连接用户已经在线"
	ConnectedUserAlreadyInChatList     = "连接用户已经在聊天列表中"
	ConnectedUserAlreadyExist          = "连接用户已经存在"
	RespWaitForResponse                = "等待响应"
	RespNoResponse                     = "没有响应"
	RespDisconnectMessagePrefix        = "disconnect-user:"
	InvalidParams                      = "参数错误"
	ConnectTimeOut                     = "连接超时"
	SendMsgSuccess                     = "发送消息成功"
	SendMsgFail                        = "发送消息失败"
	RespSendMsgSuccess                 = "发送消息成功"
	RespSendMsgFail                    = "发送消息失败"
	MessageStorageFailed               = "消息存储失败"
	SearchFailed                       = "搜索失败"
	SearchSuccess                      = "搜索成功"
	SearchNoResult                     = "没有搜索结果"
	AddedFailed                        = "添加失败"
	AddedSuccess                       = "添加成功"
	DeletedFailed                      = "删除失败"
	DeletedSuccess                     = "删除成功"
	UpdatedFailed                      = "更新失败"
	UpdatedSuccess                     = "更新成功"
	NoAuthority                        = "没有权限"
)
