server: 
  port: :19251

app: 
  publish-key: napbad-publish
  
email:
  host: smtp.qq.com
  port: 587
  sender: 3242541948@qq.com
  password: uodqzienfjhocjhc

zap:
  level: info
  format: console
  prefix: "[napbad]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
  retention-day: -1


# redis configuration
redis:
  #是否使用redis集群模式
  useCluster: false
  #使用集群模式addr和db默认无效
  addr: 8.137.87.209:19401
  password: ThisIsNapbad
  poolsize: 30
  db: 0
  clusterAddrs:
    - "172.21.0.3:7000"
    - "172.21.0.4:7001"
    - "172.21.0.2:7002"


mysql:
  host: 8.137.87.209
  port: 19501
  user: root
  password: 191019sJs_MySQL
  db: pengyou
  max-idle-conns: 10
  max-open-conns: 100
  conf: charset=utf8mb4&parseTime=True&loc=Local

files: 
  dir: /home/napbad/tmp/files/
  buf-size: 1024
  read-buf-size: 1024
  write-buf-size: 1024

