definitions:
  entity.MessageSend:
    type: object
  model.MessageConfirmRec:
    properties:
      confirm_time:
        type: string
      message_id:
        items:
          type: integer
        type: array
      user_id:
        type: integer
    type: object
  request.GetById:
    properties:
      id:
        description: 主键ID
        type: integer
    type: object
  request.PostCreateInput:
    properties:
      author:
        description: Author of the post
        type: string
      content:
        description: Content of the post
        type: string
      createdPerson:
        description: Created person ID
        type: integer
      deleteAt:
        description: Deletion timestamp
        type: string
      modifiedByAdmin:
        description: Whether modified by admin
        type: integer
      modifiedPerson:
        description: Modified person ID
        type: integer
      status:
        description: Status of the post
        type: integer
      title:
        description: Title of the post
        type: string
    type: object
  request.PostUpdateInput:
    properties:
      author:
        description: Author of the post
        type: string
      content:
        description: Content of the post
        type: string
      createdPerson:
        description: Created person ID
        type: integer
      deleteAt:
        description: Deletion timestamp
        type: string
      id:
        description: ID of the post
        type: integer
      modifiedByAdmin:
        description: Whether modified by admin
        type: integer
      modifiedPerson:
        description: Modified person ID
        type: integer
      status:
        description: Status of the post
        type: integer
      title:
        description: Title of the post
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /chat/confirm-receive:
    post:
      consumes:
      - application/json
      description: Confirms that a message has been received.
      parameters:
      - description: Confirmation details
        in: body
        name: confirmation
        required: true
        schema:
          $ref: '#/definitions/model.MessageConfirmRec'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Confirm receipt of a message
      tags:
      - messages
  /chat/get-unread-msg:
    post:
      consumes:
      - application/json
      description: Retrieves unread messages for a user.
      parameters:
      - description: User ID
        in: formData
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get unread messages
      tags:
      - messages
  /chat/leave-msg:
    post:
      consumes:
      - application/json
      description: Sends a new message between users.
      parameters:
      - description: The message details
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/entity.MessageSend'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Send a new message
      tags:
      - messages
  /connect/cut-chat-from:
    post:
      consumes:
      - application/json
      description: Cuts off a chat session with another user.
      parameters:
      - description: User ID
        in: header
        name: userId
        required: true
        type: string
      - description: Chatter ID
        in: formData
        name: chatterId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Cut off a chat session
      tags:
      - chat
  /connect/establish:
    post:
      consumes:
      - application/json
      description: Establishes a new WebSocket connection for a user.
      parameters:
      - description: User ID
        in: header
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Establish a new connection
      tags:
      - connections
  /connect/establish-chat-to:
    post:
      consumes:
      - application/json
      description: Establishes a chat session with another user.
      parameters:
      - description: User ID
        in: header
        name: userId
        required: true
        type: string
      - description: Chatter ID
        in: formData
        name: chatterId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Establish a chat session
      tags:
      - chat
  /connect/heart-beat:
    post:
      consumes:
      - application/json
      description: Checks the heartbeat of a user to maintain the connection.
      parameters:
      - description: User ID
        in: header
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Heartbeat for user connection
      tags:
      - connections
  /connect/shutdown:
    post:
      consumes:
      - application/json
      description: Shuts down an existing WebSocket connection for a user.
      parameters:
      - description: User ID
        in: header
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Shutdown an existing connection
      tags:
      - connections
  /posts:
    delete:
      consumes:
      - application/json
      description: 删除指定 ID 的帖子
      parameters:
      - description: 帖子 ID
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/request.GetById'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 无效参数
          schema:
            $ref: '#/definitions/response.Response'
      tags:
      - 帖子
    post:
      consumes:
      - application/json
      description: 添加新的帖子
      parameters:
      - description: 帖子信息
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/request.PostCreateInput'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 无效参数
          schema:
            $ref: '#/definitions/response.Response'
      tags:
      - 帖子
    put:
      consumes:
      - application/json
      description: 更新帖子的信息
      parameters:
      - description: 帖子信息
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/request.PostUpdateInput'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 无效参数
          schema:
            $ref: '#/definitions/response.Response'
      tags:
      - 帖子
  /test:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: 'name": "Napbad", "func": "test"}'
          schema:
            type: string
      summary: ping example
      tags:
      - example
swagger: "2.0"
