info:
  contact: {}
paths:
  /test:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: 'name": "Napbad", "func": "test"}'
          schema:
            type: string
      summary: ping example
      tags:
      - example
swagger: "2.0"
