version: '3.8'

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus_pengyou
    hostname: prometheus
    ports:
      - 19001:9090
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana_pengyou
    hostname: grafana
    ports:
      - 19051:3000
    volumes:  
      - ./grafana:/etc/grafana

  redis:
    image: redis
    container_name: redis-for-lock
    
    hostname: redis
    ports:
      - 9100:6379
    volumes:
      - ./redis/for-lock/data:/data
      - ./redis/for-lock/conf:/usr/local/etc/redis
    command:
      redis-server /usr/local/etc/redis/redis.conf